### PR TITLE
 Updating spec with documentation and adding fields to metadata

### PR DESCRIPTION
**Pull request by slebras**

### CODE REVIEW

**Comment by slebras** [comment]
Fixing indentation, so diff appears larger

**Comment by dcchivian** [comment]
@slebras is the "environment" metadata aligned with other sample and ontology design in the system?  or did we just decide to push forward with having something here to get movement in the area without having to delay an longer?

**Comment by dcchivian** [comment]
@slebras anyway, I'm fine with these changes from my narrow perspective, but I lack merge permission.  @sychan @sychan @psdehal if you'd like to do the honors?

**Comment by Yzm1234** [comment]
see #58

**Pull request closed without merging**
